const datos = {
  pacientes: [
    {
      id: 1,
      nombre: "Chelsea Navarro",
      dni: 44657814,
      email: "christophershepherd@barnes-fletcher.net",
      telefono: "093-823-5538x3262",
      fechaNacimiento: "1951-05-30",
      sexo: "Otro",
      direccion: "8068 Allison Rapid, Davidbury, IL 16632",
      seguroMedico: "Adeslas",
    },
    {
      id: 2,
      nombre: "Brandi Ramirez",
      dni: 64003488,
      email: "hgordon@mckinney.com",
      telefono: "001-986-155-8104",
      fechaNacimiento: "1946-04-24",
      sexo: "Otro",
      direccion: "5469 Joanna Ways Suite 378, Angelafort, AR 72723",
      seguroMedico: "Adeslas",
    },
    {
      id: 3,
      nombre: "Alyssa Phillips",
      dni: 20780658,
      email: "patrickavery@solis-dalton.com",
      telefono: "(077)394-3372",
      fechaNacimiento: "1945-05-21",
      sexo: "Femenino",
      direccion: "288 Bray Forest Suite 214, Leehaven, OH 28550",
      seguroMedico: "Sanitas",
    },
    {
      id: 4,
      nombre: "Isaac Peck",
      dni: 36925142,
      email: "andersonsarah@jones.com",
      telefono: "001-882-414-7551x370",
      fechaNacimiento: "1959-09-15",
      sexo: "Femenino",
      direccion: "11922 Teresa Port Apt. 681, Port Theresaport, MO 27032",
      seguroMedico: "Mapfre",
    },
    {
      id: 5,
      nombre: "Alexander Harris",
      dni: 93956413,
      email: "fwilson@martinez.net",
      telefono: "001-513-427-7389x6152",
      fechaNacimiento: "1975-09-08",
      sexo: "Otro",
      direccion: "2087 Mariah Mission Suite 457, South Kevinport, MD 43083",
      seguroMedico: "Sanitas",
    },
    {
      id: 6,
      nombre: "Brian Lynch",
      dni: 41449739,
      email: "robinsonmatthew@gmail.com",
      telefono: "(382)459-9454",
      fechaNacimiento: "2005-07-31",
      sexo: "Masculino",
      direccion: "69107 Kiara Ford Apt. 154, Stephaniemouth, DE 04311",
      seguroMedico: "Mapfre",
    },
    {
      id: 7,
      nombre: "Charles Hill",
      dni: 32438143,
      email: "nicholas39@lara.com",
      telefono: "+1-860-726-4878",
      fechaNacimiento: "1969-10-04",
      sexo: "Masculino",
      direccion: "419 Matthew Pike, Lake Richard, MD 34553",
      seguroMedico: "Adeslas",
    },
    {
      id: 8,
      nombre: "Sara Becker",
      dni: 82937536,
      email: "kleintim@cowan.com",
      telefono: "269-658-0561",
      fechaNacimiento: "2005-10-07",
      sexo: "Otro",
      direccion: "314 Carlos Trail Suite 769, South Jeremy, DC 84785",
      seguroMedico: "Mapfre",
    },
    {
      id: 9,
      nombre: "Mr. Jonathon Rodriguez",
      dni: 81164199,
      email: "kjacobson@lopez-ruiz.com",
      telefono: "+1-524-608-0949x705",
      fechaNacimiento: "1947-04-19",
      sexo: "Otro",
      direccion: "36837 Sims Spur Apt. 243, Port Tyronehaven, IA 22457",
      seguroMedico: "Adeslas",
    },
    {
      id: 10,
      nombre: "Cory Ramirez",
      dni: 94792926,
      email: "heidi73@hotmail.com",
      telefono: "+1-089-663-1047x77190",
      fechaNacimiento: "1975-03-28",
      sexo: "Femenino",
      direccion: "858 Melton Run, East Alecstad, ME 72653",
      seguroMedico: "Mapfre",
    },
    {
      id: 11,
      nombre: "Mary Harris",
      dni: 87156901,
      email: "gbowman@hotmail.com",
      telefono: "4318604577",
      fechaNacimiento: "1995-03-01",
      sexo: "Masculino",
      direccion: "USS Day, FPO AP 56721",
      seguroMedico: null,
    },
    {
      id: 12,
      nombre: "Jeffery Miller",
      dni: 43043303,
      email: "bstewart@hotmail.com",
      telefono: "360-516-6530",
      fechaNacimiento: "1971-08-03",
      sexo: "Femenino",
      direccion: "418 Jamie Street, Patelton, TX 48254",
      seguroMedico: null,
    },
    {
      id: 13,
      nombre: "Nicole Ferguson",
      dni: 81821352,
      email: "victor13@yahoo.com",
      telefono: "835.214.2391",
      fechaNacimiento: "1970-03-22",
      sexo: "Otro",
      direccion: "0142 Elizabeth Coves, Heatherbury, MA 67315",
      seguroMedico: "Adeslas",
    },
    {
      id: 14,
      nombre: "Miranda Jones",
      dni: 35046461,
      email: "michael89@hughes.net",
      telefono: "028-359-6739",
      fechaNacimiento: "2000-09-14",
      sexo: "Femenino",
      direccion: "574 Harrison Trail, Mullenville, AR 84045",
      seguroMedico: "Sanitas",
    },
    {
      id: 15,
      nombre: "Tina Smith",
      dni: 20188022,
      email: "lukedean@yahoo.com",
      telefono: "689-546-9921",
      fechaNacimiento: "1989-06-13",
      sexo: "Masculino",
      direccion: "4146 Harris Road, Clarkchester, SD 16358",
      seguroMedico: "Sanitas",
    },
    {
      id: 16,
      nombre: "Michele Edwards",
      dni: 24042136,
      email: "jesusmcgee@henry.com",
      telefono: "428-908-7228x88760",
      fechaNacimiento: "1988-10-07",
      sexo: "Femenino",
      direccion: "516 Theresa Shore, South Karen, CT 37814",
      seguroMedico: "Adeslas",
    },
    {
      id: 17,
      nombre: "Todd Francis",
      dni: 98845327,
      email: "burtonlori@hotmail.com",
      telefono: "001-527-036-1485",
      fechaNacimiento: "1961-03-17",
      sexo: "Femenino",
      direccion: "Unit 2543 Box 8207, DPO AE 58852",
      seguroMedico: null,
    },
    {
      id: 18,
      nombre: "Chad Waters",
      dni: 90239476,
      email: "olivervincent@pena.com",
      telefono: "(340)381-2738x359",
      fechaNacimiento: "2005-09-19",
      sexo: "Femenino",
      direccion: "05626 Jason Drive, Crystaltown, CA 48653",
      seguroMedico: "Mapfre",
    },
    {
      id: 19,
      nombre: "Douglas Jones",
      dni: 39752664,
      email: "jeanette63@lucas.com",
      telefono: "221-516-5762",
      fechaNacimiento: "1959-04-13",
      sexo: "Masculino",
      direccion: "PSC 7574, Box 6613, APO AP 82480",
      seguroMedico: null,
    },
    {
      id: 20,
      nombre: "Dana Chavez",
      dni: 31042352,
      email: "hectorcunningham@yahoo.com",
      telefono: "+1-150-478-4599x300",
      fechaNacimiento: "1959-01-12",
      sexo: "Otro",
      direccion: "962 Craig Islands, Frenchchester, HI 96186",
      seguroMedico: "Adeslas",
    },
    {
      id: 21,
      nombre: "Christopher Meza",
      dni: 56315001,
      email: "kingmaria@lewis.info",
      telefono: "(071)310-4262",
      fechaNacimiento: "2005-01-15",
      sexo: "Masculino",
      direccion: "0612 Davis Islands, East Jadeport, CA 64713",
      seguroMedico: "Adeslas",
    },
    {
      id: 22,
      nombre: "Nicole Bennett",
      dni: 25698975,
      email: "jeffreycortez@lara-craig.com",
      telefono: "0536236135",
      fechaNacimiento: "1936-08-26",
      sexo: "Femenino",
      direccion: "01458 Gwendolyn Extensions, Perezmouth, IN 78275",
      seguroMedico: null,
    },
    {
      id: 23,
      nombre: "Zachary Hubbard",
      dni: 48799437,
      email: "patelcaroline@yahoo.com",
      telefono: "001-382-301-7853x7896",
      fechaNacimiento: "1989-11-13",
      sexo: "Otro",
      direccion: "3182 Drake Ville, Burtontown, IA 34413",
      seguroMedico: "Adeslas",
    },
    {
      id: 24,
      nombre: "Sharon Johnson",
      dni: 33835277,
      email: "shannonsmith@mcgee.com",
      telefono: "(687)469-4975x317",
      fechaNacimiento: "1971-11-27",
      sexo: "Otro",
      direccion: "895 Catherine Underpass Apt. 127, Jeremyfort, UT 84535",
      seguroMedico: "Sanitas",
    },
    {
      id: 25,
      nombre: "Joel Kaufman",
      dni: 15529877,
      email: "thomasjessica@gmail.com",
      telefono: "251.160.5873x6024",
      fechaNacimiento: "2000-05-19",
      sexo: "Otro",
      direccion: "50917 Rocha Creek Suite 212, Lovefort, OR 40404",
      seguroMedico: null,
    },
    {
      id: 26,
      nombre: "Christopher Holland",
      dni: 99225207,
      email: "cory84@jones.com",
      telefono: "001-579-850-6655x624",
      fechaNacimiento: "1939-10-20",
      sexo: "Otro",
      direccion: "488 Castro Track Suite 039, West Stephen, IL 45407",
      seguroMedico: null,
    },
    {
      id: 27,
      nombre: "Cindy Howe",
      dni: 52328596,
      email: "smithlindsey@duarte.com",
      telefono: "(311)260-9993",
      fechaNacimiento: "1956-08-13",
      sexo: "Masculino",
      direccion: "43872 Clark Mountain Suite 560, East Patrick, FL 34915",
      seguroMedico: "Mapfre",
    },
    {
      id: 28,
      nombre: "Alyssa Cooley",
      dni: 35677241,
      email: "moraleswayne@yahoo.com",
      telefono: "377-961-3819",
      fechaNacimiento: "1959-11-23",
      sexo: "Femenino",
      direccion: "0293 Lindsey Mall Apt. 576, North Melissa, OR 33275",
      seguroMedico: "Adeslas",
    },
    {
      id: 29,
      nombre: "Patrick Gibbs",
      dni: 15562861,
      email: "phillipdavis@fischer.com",
      telefono: "326.143.9521x8671",
      fechaNacimiento: "1954-09-03",
      sexo: "Femenino",
      direccion: "8264 Sarah Bypass, North Rhondaburgh, SD 64708",
      seguroMedico: "Sanitas",
    },
    {
      id: 30,
      nombre: "Jennifer Silva",
      dni: 79883562,
      email: "jonathandillon@gmail.com",
      telefono: "(025)166-8508",
      fechaNacimiento: "1979-08-01",
      sexo: "Masculino",
      direccion: "15955 Lee Burg Apt. 812, Port David, WV 30659",
      seguroMedico: "Adeslas",
    },
    {
      id: 31,
      nombre: "Crystal Edwards",
      dni: 77405349,
      email: "samuel16@rodriguez.com",
      telefono: "001-100-023-4945x2200",
      fechaNacimiento: "1999-01-09",
      sexo: "Masculino",
      direccion: "PSC 8611, Box 0344, APO AP 94208",
      seguroMedico: "Mapfre",
    },
    {
      id: 32,
      nombre: "Morgan Petersen",
      dni: 83075877,
      email: "frogers@hotmail.com",
      telefono: "+1-909-548-7896x815",
      fechaNacimiento: "1945-02-04",
      sexo: "Otro",
      direccion: "Unit 9979 Box 0297, DPO AP 87072",
      seguroMedico: "Mapfre",
    },
    {
      id: 33,
      nombre: "Wayne Thomas",
      dni: 73117272,
      email: "savannah03@gmail.com",
      telefono: "+1-769-272-4347",
      fechaNacimiento: "1985-07-21",
      sexo: "Femenino",
      direccion: "6427 Gregory Ports Suite 601, East Timothy, OK 88307",
      seguroMedico: null,
    },
    {
      id: 34,
      nombre: "Harold Butler",
      dni: 56215170,
      email: "millerrachel@tucker-hicks.net",
      telefono: "611.610.3817x001",
      fechaNacimiento: "1971-04-09",
      sexo: "Femenino",
      direccion: "3186 Barrett Station, New Shaneberg, WI 69340",
      seguroMedico: "Sanitas",
    },
    {
      id: 35,
      nombre: "Sara Mcmillan",
      dni: 44345225,
      email: "jvillarreal@perez-erickson.net",
      telefono: "429.512.9904",
      fechaNacimiento: "1991-06-22",
      sexo: "Otro",
      direccion: "030 Marshall Plaza, Lake Sarahburgh, PA 02508",
      seguroMedico: "Adeslas",
    },
    {
      id: 36,
      nombre: "George Ramirez",
      dni: 55260572,
      email: "curtis47@gmail.com",
      telefono: "+1-487-837-1124x084",
      fechaNacimiento: "1992-03-19",
      sexo: "Otro",
      direccion: "50822 Jeremy Summit Apt. 400, Heatherborough, CO 36390",
      seguroMedico: null,
    },
    {
      id: 37,
      nombre: "Stacy Carpenter",
      dni: 51657602,
      email: "claire34@yahoo.com",
      telefono: "(873)111-4486",
      fechaNacimiento: "1949-11-30",
      sexo: "Femenino",
      direccion: "788 Kimberly Freeway Suite 151, New Andrew, ND 68510",
      seguroMedico: "Sanitas",
    },
    {
      id: 38,
      nombre: "Jose Dawson",
      dni: 64698866,
      email: "wrightsamantha@hotmail.com",
      telefono: "727-909-7891",
      fechaNacimiento: "1944-12-17",
      sexo: "Masculino",
      direccion: "3003 Corey Locks, Jessicaview, OR 26809",
      seguroMedico: "Mapfre",
    },
    {
      id: 39,
      nombre: "Lauren Campbell",
      dni: 78989917,
      email: "ycarpenter@gmail.com",
      telefono: "862.615.5973",
      fechaNacimiento: "1962-02-21",
      sexo: "Otro",
      direccion: "78014 Elizabeth Loop Suite 022, West Michael, CT 18188",
      seguroMedico: "Mapfre",
    },
    {
      id: 40,
      nombre: "Brenda Harrison",
      dni: 61742091,
      email: "xtodd@yahoo.com",
      telefono: "(916)003-8351x77369",
      fechaNacimiento: "1986-04-01",
      sexo: "Masculino",
      direccion: "1184 Heather Underpass, Port Kentview, IA 83194",
      seguroMedico: "Mapfre",
    },
    {
      id: 41,
      nombre: "Adrian Stephens",
      dni: 23258576,
      email: "qmcconnell@combs.com",
      telefono: "0948458424",
      fechaNacimiento: "1952-10-25",
      sexo: "Masculino",
      direccion: "229 Guzman Lights Apt. 326, West Heathermouth, ME 80886",
      seguroMedico: null,
    },
    {
      id: 42,
      nombre: "Rebecca Hansen",
      dni: 88516715,
      email: "stevenhays@hotmail.com",
      telefono: "829-689-1819",
      fechaNacimiento: "1997-12-19",
      sexo: "Masculino",
      direccion: "0306 Patrick Route, North Rebekahport, NM 30466",
      seguroMedico: "Sanitas",
    },
    {
      id: 43,
      nombre: "Bruce Carson",
      dni: 42915061,
      email: "ccarter@santana.com",
      telefono: "242-260-7420x8736",
      fechaNacimiento: "1950-04-25",
      sexo: "Femenino",
      direccion: "PSC 8390, Box 6047, APO AA 59327",
      seguroMedico: "Adeslas",
    },
    {
      id: 44,
      nombre: "Laura Price",
      dni: 99168284,
      email: "bjohnson@gmail.com",
      telefono: "9692447779",
      fechaNacimiento: "1940-09-01",
      sexo: "Femenino",
      direccion: "2713 Green Summit Apt. 712, Port Erica, OK 02557",
      seguroMedico: "Adeslas",
    },
    {
      id: 45,
      nombre: "Jennifer Johnson",
      dni: 87123137,
      email: "fking@gmail.com",
      telefono: "992.569.1215x04063",
      fechaNacimiento: "1949-08-17",
      sexo: "Femenino",
      direccion: "433 Smith Mountain Apt. 171, East Ethanside, NH 63144",
      seguroMedico: "Adeslas",
    },
    {
      id: 46,
      nombre: "Stephen Williams",
      dni: 50421611,
      email: "jchaney@phillips.com",
      telefono: "099.743.9612x4765",
      fechaNacimiento: "1986-05-05",
      sexo: "Masculino",
      direccion: "USNV Ferguson, FPO AA 05928",
      seguroMedico: "Mapfre",
    },
    {
      id: 47,
      nombre: "Kristin Johnson",
      dni: 97329173,
      email: "cassie62@yahoo.com",
      telefono: "001-589-479-3180",
      fechaNacimiento: "1954-02-12",
      sexo: "Otro",
      direccion: "116 Betty Hill Apt. 277, Arnoldview, ND 83955",
      seguroMedico: "Mapfre",
    },
    {
      id: 48,
      nombre: "Cindy Mercado",
      dni: 99403010,
      email: "francisco08@yahoo.com",
      telefono: "685.890.2814x55630",
      fechaNacimiento: "1981-03-25",
      sexo: "Femenino",
      direccion: "95186 Morales Mills Apt. 857, Robertostad, GA 47636",
      seguroMedico: "Mapfre",
    },
    {
      id: 49,
      nombre: "Andrew Leonard",
      dni: 89224325,
      email: "william89@hotmail.com",
      telefono: "(432)903-5962x2240",
      fechaNacimiento: "1951-07-23",
      sexo: "Otro",
      direccion: "673 Donna Ways, New Lisaport, NY 75319",
      seguroMedico: "Mapfre",
    },
    {
      id: 50,
      nombre: "Kristy Ford",
      dni: 32199694,
      email: "grayrita@horton.org",
      telefono: "+1-136-688-0518x38219",
      fechaNacimiento: "1972-04-25",
      sexo: "Femenino",
      direccion: "79822 Riley Stravenue, Pachecochester, GA 06504",
      seguroMedico: null,
    },
    {
      id: 51,
      nombre: "James Bond",
      dni: 13471224,
      email: "kimberlykemp@parrish-ruiz.com",
      telefono: "+1-260-571-1590x9278",
      fechaNacimiento: "1987-09-11",
      sexo: "Otro",
      direccion: "499 Hawkins Ferry, Port Emilyland, TX 19326",
      seguroMedico: "Mapfre",
    },
    {
      id: 52,
      nombre: "Joseph Sullivan",
      dni: 39688989,
      email: "xsimmons@hotmail.com",
      telefono: "(690)926-6868x07428",
      fechaNacimiento: "1967-09-18",
      sexo: "Femenino",
      direccion: "63315 Jenna Pine, Fitzgeraldhaven, VT 98263",
      seguroMedico: null,
    },
    {
      id: 53,
      nombre: "Michael Fritz",
      dni: 14335168,
      email: "jenniferstewart@hotmail.com",
      telefono: "924-232-4896x63723",
      fechaNacimiento: "1961-12-27",
      sexo: "Masculino",
      direccion: "209 Jeremy Glens Suite 224, South Michaelland, WY 84951",
      seguroMedico: "Mapfre",
    },
    {
      id: 54,
      nombre: "Amy Morgan",
      dni: 31863150,
      email: "eric10@gmail.com",
      telefono: "001-751-760-4077x96837",
      fechaNacimiento: "1998-12-26",
      sexo: "Otro",
      direccion: "PSC 2265, Box 0365, APO AP 57732",
      seguroMedico: "Sanitas",
    },
    {
      id: 55,
      nombre: "Veronica Christensen",
      dni: 15037095,
      email: "lkennedy@jones-lewis.net",
      telefono: "605.652.0471",
      fechaNacimiento: "1962-11-13",
      sexo: "Masculino",
      direccion: "0748 Nicole Pines Apt. 724, Dawnberg, LA 19182",
      seguroMedico: null,
    },
    {
      id: 56,
      nombre: "Jacob Wells",
      dni: 14030262,
      email: "jill78@osborne.com",
      telefono: "082.020.1343",
      fechaNacimiento: "2002-06-09",
      sexo: "Femenino",
      direccion: "21811 Barbara Fields, Marcusmouth, MI 33768",
      seguroMedico: "Sanitas",
    },
    {
      id: 57,
      nombre: "Jennifer Reyes",
      dni: 91699303,
      email: "marthaclark@gmail.com",
      telefono: "(461)068-7569",
      fechaNacimiento: "1999-10-30",
      sexo: "Femenino",
      direccion: "240 Joshua Trail, North Dana, MT 41214",
      seguroMedico: null,
    },
    {
      id: 58,
      nombre: "Kent Cox",
      dni: 68137830,
      email: "molly22@meza-le.com",
      telefono: "942-623-3523x90243",
      fechaNacimiento: "1993-01-02",
      sexo: "Otro",
      direccion: "459 Wong Tunnel Apt. 397, Morenoshire, MA 82829",
      seguroMedico: "Adeslas",
    },
  ],
  expedientes: [
    {
      id: 1,
      pacienteId: 1,
      fechaApertura: "2023-05-23",
      antecedentes: "Covid-19",
      diagnosticos: "Alergia estacional",
      tratamientos: "Ibuprofeno 400mg, Antihistamínicos",
      observaciones: "Threat true he discussion continue woman yes fall.",
    },
    {
      id: 2,
      pacienteId: 2,
      fechaApertura: "2023-01-25",
      antecedentes: "Hipertensión",
      diagnosticos: "Asma",
      tratamientos: "Ibuprofeno 400mg",
      observaciones:
        "Already news professional become their argue contain tonight.",
    },
    {
      id: 3,
      pacienteId: 3,
      fechaApertura: "2021-05-27",
      antecedentes: "Asma, Migraña, Covid-19",
      diagnosticos: "Asma, Migraña, Hipertensión",
      tratamientos: "Dieta baja en sodio",
      observaciones:
        "Fly magazine easy huge sit police help second political school change care.",
    },
    {
      id: 4,
      pacienteId: 4,
      fechaApertura: "2020-09-24",
      antecedentes: "Gripe, Asma, Migraña",
      diagnosticos: "Hipertensión, Asma",
      tratamientos: "Insulina, Ventolín",
      observaciones:
        "Wide effort call significant off age every personal nearly.",
    },
    {
      id: 5,
      pacienteId: 5,
      fechaApertura: "2024-03-03",
      antecedentes: "Alergia estacional, Diabetes",
      diagnosticos: "Gripe",
      tratamientos: "Insulina, Ventolín",
      observaciones:
        "Keep theory bed understand let fish bank bag matter life.",
    },
    {
      id: 6,
      pacienteId: 6,
      fechaApertura: "2020-08-27",
      antecedentes: "Migraña, Diabetes",
      diagnosticos: "Hipertensión",
      tratamientos: "Insulina, Paracetamol 500mg",
      observaciones:
        "Interview sign charge likely draw right responsibility thus.",
    },
    {
      id: 7,
      pacienteId: 7,
      fechaApertura: "2022-02-02",
      antecedentes: "Hipertensión, Diabetes",
      diagnosticos: "Migraña, Covid-19",
      tratamientos: "Dieta baja en sodio",
      observaciones:
        "Surface although skin really edge history explain risk daughter.",
    },
    {
      id: 8,
      pacienteId: 8,
      fechaApertura: "2021-08-17",
      antecedentes: "Asma, Migraña, Hipertensión",
      diagnosticos: "Asma",
      tratamientos: "Insulina, Ibuprofeno 400mg",
      observaciones: "Poor seem Democrat now home certainly.",
    },
    {
      id: 9,
      pacienteId: 9,
      fechaApertura: "2020-11-28",
      antecedentes: "Diabetes",
      diagnosticos: "Asma, Hipertensión",
      tratamientos: "Ibuprofeno 400mg, Dieta baja en sodio",
      observaciones:
        "Edge possible yard idea simple make happy modern attention go.",
    },
    {
      id: 10,
      pacienteId: 10,
      fechaApertura: "2024-02-03",
      antecedentes: "Migraña, Covid-19",
      diagnosticos: "Alergia estacional, Diabetes",
      tratamientos: "Ventolín",
      observaciones: "Wish loss weight future ready hour art think.",
    },
    {
      id: 11,
      pacienteId: 11,
      fechaApertura: "2023-03-03",
      antecedentes: "Diabetes",
      diagnosticos: "Covid-19, Asma, Gripe",
      tratamientos: "Insulina",
      observaciones:
        "Camera enough everyone appear what take service food act within.",
    },
    {
      id: 12,
      pacienteId: 12,
      fechaApertura: "2021-06-19",
      antecedentes: "Diabetes, Alergia estacional, Migraña",
      diagnosticos: "Alergia estacional",
      tratamientos: "Insulina",
      observaciones:
        "New worker turn include major long main order economy way million.",
    },
    {
      id: 13,
      pacienteId: 13,
      fechaApertura: "2023-12-19",
      antecedentes: "Gripe, Alergia estacional",
      diagnosticos: "Hipertensión, Diabetes",
      tratamientos: "Ventolín",
      observaciones: "Couple popular night ability wish town.",
    },
    {
      id: 14,
      pacienteId: 14,
      fechaApertura: "2020-05-20",
      antecedentes: "Diabetes, Gripe",
      diagnosticos: "Alergia estacional, Asma, Gripe",
      tratamientos: "Ventolín, Paracetamol 500mg",
      observaciones:
        "Politics indeed watch teacher like present show land spring official TV force push.",
    },
    {
      id: 15,
      pacienteId: 15,
      fechaApertura: "2024-12-09",
      antecedentes: "Migraña, Gripe",
      diagnosticos: "Gripe, Alergia estacional",
      tratamientos: "Ventolín, Dieta baja en sodio",
      observaciones:
        "Voice art remember leader get represent move trouble officer throw special.",
    },
    {
      id: 16,
      pacienteId: 16,
      fechaApertura: "2020-10-02",
      antecedentes: "Hipertensión, Migraña",
      diagnosticos: "Covid-19, Gripe, Migraña",
      tratamientos: "Ventolín, Paracetamol 500mg",
      observaciones: "Big loss training outside could party.",
    },
    {
      id: 17,
      pacienteId: 17,
      fechaApertura: "2020-02-01",
      antecedentes: "Migraña",
      diagnosticos: "Diabetes, Migraña",
      tratamientos: "Insulina",
      observaciones:
        "Him through success well per late college report democratic turn enter treat budget.",
    },
    {
      id: 18,
      pacienteId: 18,
      fechaApertura: "2023-05-05",
      antecedentes: "Gripe",
      diagnosticos: "Migraña, Asma",
      tratamientos: "Ventolín, Ibuprofeno 400mg",
      observaciones:
        "Could cell possible sea child government sense every wait my.",
    },
    {
      id: 19,
      pacienteId: 19,
      fechaApertura: "2024-06-09",
      antecedentes: "Hipertensión, Gripe",
      diagnosticos: "Hipertensión",
      tratamientos: "Paracetamol 500mg",
      observaciones:
        "No structure development human true visit determine able lead understand available.",
    },
    {
      id: 20,
      pacienteId: 20,
      fechaApertura: "2020-03-21",
      antecedentes: "Covid-19",
      diagnosticos: "Alergia estacional, Asma",
      tratamientos: "Ibuprofeno 400mg, Paracetamol 500mg",
      observaciones: "Thought body structure seek central station tree large.",
    },
    {
      id: 21,
      pacienteId: 21,
      fechaApertura: "2021-07-26",
      antecedentes: "Gripe, Migraña",
      diagnosticos: "Diabetes",
      tratamientos: "Dieta baja en sodio, Antihistamínicos",
      observaciones:
        "Senior anyone onto happen investment player what open where.",
    },
    {
      id: 22,
      pacienteId: 22,
      fechaApertura: "2024-07-22",
      antecedentes: "Hipertensión",
      diagnosticos: "Diabetes",
      tratamientos: "Dieta baja en sodio, Antihistamínicos",
      observaciones: "Specific deal chair operation statement simple full.",
    },
    {
      id: 23,
      pacienteId: 23,
      fechaApertura: "2024-12-17",
      antecedentes: "Hipertensión, Covid-19, Gripe",
      diagnosticos: "Alergia estacional, Hipertensión, Gripe",
      tratamientos: "Ibuprofeno 400mg, Insulina",
      observaciones:
        "Professor across every drive recently positive coach woman smile.",
    },
    {
      id: 24,
      pacienteId: 24,
      fechaApertura: "2023-06-22",
      antecedentes: "Asma, Hipertensión",
      diagnosticos: "Hipertensión",
      tratamientos: "Insulina",
      observaciones:
        "Good south member across who herself debate window save cup sport century.",
    },
    {
      id: 25,
      pacienteId: 25,
      fechaApertura: "2021-08-03",
      antecedentes: "Alergia estacional",
      diagnosticos: "Alergia estacional, Covid-19",
      tratamientos: "Dieta baja en sodio",
      observaciones:
        "This account say stock reflect first bring anyone attorney.",
    },
    {
      id: 26,
      pacienteId: 26,
      fechaApertura: "2024-11-28",
      antecedentes: "Alergia estacional",
      diagnosticos: "Asma, Gripe, Hipertensión",
      tratamientos: "Dieta baja en sodio, Paracetamol 500mg",
      observaciones:
        "Seek mind population child participant foot game teacher court.",
    },
    {
      id: 27,
      pacienteId: 27,
      fechaApertura: "2022-06-08",
      antecedentes: "Migraña, Diabetes",
      diagnosticos: "Migraña",
      tratamientos: "Ventolín",
      observaciones:
        "Own drug whatever she camera statement nature blue despite model.",
    },
    {
      id: 28,
      pacienteId: 28,
      fechaApertura: "2020-03-09",
      antecedentes: "Gripe",
      diagnosticos: "Asma, Covid-19",
      tratamientos: "Paracetamol 500mg",
      observaciones: "Manager once person run west election mind book.",
    },
    {
      id: 29,
      pacienteId: 29,
      fechaApertura: "2023-03-20",
      antecedentes: "Diabetes",
      diagnosticos: "Diabetes, Migraña",
      tratamientos: "Ibuprofeno 400mg, Paracetamol 500mg",
      observaciones:
        "Want receive of story our music allow technology want film that administration Republican.",
    },
    {
      id: 30,
      pacienteId: 30,
      fechaApertura: "2024-04-26",
      antecedentes: "Asma, Diabetes, Covid-19",
      diagnosticos: "Gripe, Asma",
      tratamientos: "Dieta baja en sodio, Paracetamol 500mg",
      observaciones:
        "Last speech trial loss message size question clearly put page interest.",
    },
    {
      id: 31,
      pacienteId: 31,
      fechaApertura: "2020-03-29",
      antecedentes: "Alergia estacional, Diabetes",
      diagnosticos: "Migraña, Hipertensión",
      tratamientos: "Paracetamol 500mg",
      observaciones:
        "Free child foreign rich heavy factor see white bit human.",
    },
    {
      id: 32,
      pacienteId: 32,
      fechaApertura: "2021-05-14",
      antecedentes: "Migraña, Hipertensión, Asma",
      diagnosticos: "Asma, Gripe",
      tratamientos: "Dieta baja en sodio, Ventolín",
      observaciones: "Many keep tough the throw standard should.",
    },
    {
      id: 33,
      pacienteId: 33,
      fechaApertura: "2022-08-09",
      antecedentes: "Asma, Diabetes, Alergia estacional",
      diagnosticos: "Asma",
      tratamientos: "Ibuprofeno 400mg, Antihistamínicos",
      observaciones:
        "Conference each I key include example quickly executive could act scientist current.",
    },
    {
      id: 34,
      pacienteId: 34,
      fechaApertura: "2020-04-10",
      antecedentes: "Gripe, Covid-19",
      diagnosticos: "Covid-19, Diabetes",
      tratamientos: "Ventolín, Insulina",
      observaciones:
        "Build every speak trip process bring issue vote serious responsibility sense son.",
    },
    {
      id: 35,
      pacienteId: 35,
      fechaApertura: "2022-12-10",
      antecedentes: "Gripe, Diabetes, Covid-19",
      diagnosticos: "Hipertensión, Covid-19, Alergia estacional",
      tratamientos: "Ventolín",
      observaciones:
        "Degree field close forget animal meeting put three enjoy story child.",
    },
    {
      id: 36,
      pacienteId: 36,
      fechaApertura: "2020-12-31",
      antecedentes: "Hipertensión, Asma",
      diagnosticos: "Migraña",
      tratamientos: "Ibuprofeno 400mg",
      observaciones:
        "Information stock actually land store rise serve few across cost able.",
    },
    {
      id: 37,
      pacienteId: 37,
      fechaApertura: "2023-08-19",
      antecedentes: "Asma, Migraña",
      diagnosticos: "Gripe, Covid-19",
      tratamientos: "Antihistamínicos, Insulina",
      observaciones: "Early class address mouth action war.",
    },
    {
      id: 38,
      pacienteId: 38,
      fechaApertura: "2024-03-21",
      antecedentes: "Covid-19",
      diagnosticos: "Asma, Gripe",
      tratamientos: "Dieta baja en sodio",
      observaciones: "General decision pull reason whole democratic.",
    },
    {
      id: 39,
      pacienteId: 39,
      fechaApertura: "2021-10-18",
      antecedentes: "Covid-19, Diabetes, Asma",
      diagnosticos: "Covid-19, Asma",
      tratamientos: "Ventolín, Insulina",
      observaciones:
        "As cold kind great fill else take program seem return debate public catch.",
    },
    {
      id: 40,
      pacienteId: 40,
      fechaApertura: "2021-12-21",
      antecedentes: "Asma",
      diagnosticos: "Alergia estacional",
      tratamientos: "Ibuprofeno 400mg",
      observaciones: "Scene person natural cut she concern scientist.",
    },
    {
      id: 41,
      pacienteId: 41,
      fechaApertura: "2023-08-03",
      antecedentes: "Hipertensión, Asma",
      diagnosticos: "Gripe, Asma",
      tratamientos: "Paracetamol 500mg",
      observaciones: "None peace ability draw mouth hard image.",
    },
    {
      id: 42,
      pacienteId: 42,
      fechaApertura: "2021-07-07",
      antecedentes: "Diabetes",
      diagnosticos: "Covid-19, Hipertensión, Asma",
      tratamientos: "Antihistamínicos, Ventolín",
      observaciones:
        "Interest business respond ground build sing season everyone once participant whole quality.",
    },
    {
      id: 43,
      pacienteId: 43,
      fechaApertura: "2020-12-15",
      antecedentes: "Gripe, Diabetes, Covid-19",
      diagnosticos: "Hipertensión, Migraña, Asma",
      tratamientos: "Antihistamínicos",
      observaciones:
        "Blood natural lay step employee report be clear movie million.",
    },
    {
      id: 44,
      pacienteId: 44,
      fechaApertura: "2023-09-13",
      antecedentes: "Alergia estacional, Covid-19, Migraña",
      diagnosticos: "Gripe",
      tratamientos: "Antihistamínicos, Dieta baja en sodio",
      observaciones: "Order treat economic require present sit next senior.",
    },
    {
      id: 45,
      pacienteId: 45,
      fechaApertura: "2024-07-12",
      antecedentes: "Gripe, Migraña",
      diagnosticos: "Migraña, Alergia estacional, Asma",
      tratamientos: "Paracetamol 500mg, Ibuprofeno 400mg",
      observaciones:
        "Maybe necessary my anything no daughter choice quite statement.",
    },
    {
      id: 46,
      pacienteId: 46,
      fechaApertura: "2021-10-25",
      antecedentes: "Gripe, Asma, Migraña",
      diagnosticos: "Asma, Gripe, Diabetes",
      tratamientos: "Insulina, Antihistamínicos",
      observaciones:
        "Theory receive task blue religious best leave line blood compare.",
    },
    {
      id: 47,
      pacienteId: 47,
      fechaApertura: "2024-04-12",
      antecedentes: "Migraña",
      diagnosticos: "Covid-19, Gripe",
      tratamientos: "Dieta baja en sodio, Paracetamol 500mg",
      observaciones: "Anything law he base idea law girl he item.",
    },
    {
      id: 48,
      pacienteId: 48,
      fechaApertura: "2020-12-04",
      antecedentes: "Alergia estacional",
      diagnosticos: "Hipertensión, Migraña",
      tratamientos: "Dieta baja en sodio",
      observaciones:
        "Action himself experience thought woman weight stage business.",
    },
    {
      id: 49,
      pacienteId: 49,
      fechaApertura: "2022-02-08",
      antecedentes: "Covid-19",
      diagnosticos: "Covid-19, Gripe",
      tratamientos: "Antihistamínicos",
      observaciones:
        "Worry professor point painting view several everybody choose close should structure.",
    },
    {
      id: 50,
      pacienteId: 50,
      fechaApertura: "2024-03-22",
      antecedentes: "Migraña",
      diagnosticos: "Covid-19, Asma, Migraña",
      tratamientos: "Dieta baja en sodio, Ibuprofeno 400mg",
      observaciones:
        "Candidate go together player present article risk market national structure feeling rise capital.",
    },
    {
      id: 51,
      pacienteId: 51,
      fechaApertura: "2021-06-05",
      antecedentes: "Covid-19",
      diagnosticos: "Gripe, Migraña",
      tratamientos: "Ventolín",
      observaciones:
        "Long sing star amount when speak there risk network decide job.",
    },
    {
      id: 52,
      pacienteId: 52,
      fechaApertura: "2024-09-12",
      antecedentes: "Hipertensión, Diabetes",
      diagnosticos: "Migraña",
      tratamientos: "Antihistamínicos",
      observaciones: "Data east wrong focus at use easy Mrs whom.",
    },
    {
      id: 53,
      pacienteId: 53,
      fechaApertura: "2021-11-25",
      antecedentes: "Hipertensión, Migraña",
      diagnosticos: "Hipertensión, Diabetes",
      tratamientos: "Paracetamol 500mg, Ibuprofeno 400mg",
      observaciones:
        "Notice expect next consider suggest increase listen blue sport happen.",
    },
    {
      id: 54,
      pacienteId: 54,
      fechaApertura: "2022-05-21",
      antecedentes: "Gripe, Migraña",
      diagnosticos: "Gripe",
      tratamientos: "Insulina",
      observaciones:
        "Room why leave represent her collection although college small culture.",
    },
    {
      id: 55,
      pacienteId: 55,
      fechaApertura: "2023-07-06",
      antecedentes: "Gripe, Migraña",
      diagnosticos: "Gripe",
      tratamientos: "Dieta baja en sodio, Paracetamol 500mg",
      observaciones:
        "Leg shoulder class now situation issue boy standard message individual.",
    },
    {
      id: 56,
      pacienteId: 56,
      fechaApertura: "2021-10-04",
      antecedentes: "Alergia estacional, Hipertensión",
      diagnosticos: "Gripe, Migraña",
      tratamientos: "Dieta baja en sodio, Antihistamínicos",
      observaciones:
        "Method read tell authority may want weight month well take thousand easy another.",
    },
    {
      id: 57,
      pacienteId: 57,
      fechaApertura: "2023-08-14",
      antecedentes: "Diabetes",
      diagnosticos: "Covid-19, Gripe",
      tratamientos: "Paracetamol 500mg, Insulina",
      observaciones: "Story speech one fine say movie win.",
    },
    {
      id: 58,
      pacienteId: 58,
      fechaApertura: "2022-05-13",
      antecedentes: "Gripe, Alergia estacional, Hipertensión",
      diagnosticos: "Asma, Alergia estacional, Migraña",
      tratamientos: "Dieta baja en sodio",
      observaciones: "Computer must add me top cut modern hard listen job.",
    },
  ],
  usuarios: [
    {
      id: 1,
      username: "admin",
      password: "admin123",
      tipo: "admin",
    },
    {
      id: 2,
      username: "ana",
      password: "medico123",
      tipo: "medico",
    },
    {
      id: 3,
      username: "paco",
      password: "gestion123",
      tipo: "gestion",
    },
  ],
};

export default datos;
